# Reusable composite action for building, signing, and generating SBOMs for releases
# This action reduces duplication across pre-release, promote-release, and patch-release workflows

name: 'Build and Sign Release'
description: 'Build binaries for all platforms, sign with Cosign, and generate SBOMs'

inputs:
  version:
    description: 'Version tag (e.g., v0.1.0, v0.2.0-rc.1)'
    required: true
  ref:
    description: 'Git ref to checkout'
    required: false
    default: 'main'
  upload-artifacts:
    description: 'Whether to upload artifacts (true) or just build locally (false)'
    required: false
    default: 'true'

outputs:
  dist-path:
    description: 'Path to the dist directory containing all artifacts'
    value: ${{ steps.paths.outputs.dist }}
  checksums:
    description: 'Base64 encoded SHA256 checksums for SLSA'
    value: ${{ steps.checksums.outputs.hashes }}

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: 0

    - name: Setup mise
      uses: ./.github/actions/setup-mise

    - name: Set output paths
      id: paths
      shell: bash
      run: |
        DIST_DIR="$GITHUB_WORKSPACE/dist"
        mkdir -p "$DIST_DIR"
        echo "dist=$DIST_DIR" >> $GITHUB_OUTPUT

    - name: Build for all platforms
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        # Disabled for cross-compilation and static binaries
        CGO_ENABLED: 0
      run: |
        DIST_DIR="${{ steps.paths.outputs.dist }}"
        mise set CGO_ENABLED=${CGO_ENABLED}

        echo "ðŸ”¨ Building uptool $VERSION for 7 platforms..."
        echo "Using embedded VERSION file (no ldflags needed)"
        echo "CGO disabled for static cross-compilation"

        # Linux AMD64
        echo "  Building linux-amd64..."
        GOOS=linux GOARCH=amd64 go build -o "$DIST_DIR/uptool-linux-amd64" ./cmd/uptool

        # Linux ARM64
        echo "  Building linux-arm64..."
        GOOS=linux GOARCH=arm64 go build -o "$DIST_DIR/uptool-linux-arm64" ./cmd/uptool

        # macOS AMD64
        echo "  Building darwin-amd64..."
        GOOS=darwin GOARCH=amd64 go build -o "$DIST_DIR/uptool-darwin-amd64" ./cmd/uptool

        # macOS ARM64 (Apple Silicon)
        echo "  Building darwin-arm64..."
        GOOS=darwin GOARCH=arm64 go build -o "$DIST_DIR/uptool-darwin-arm64" ./cmd/uptool

        # Windows AMD64
        echo "  Building windows-amd64..."
        GOOS=windows GOARCH=amd64 go build -o "$DIST_DIR/uptool-windows-amd64.exe" ./cmd/uptool

        # Windows ARM64
        echo "  Building windows-arm64..."
        GOOS=windows GOARCH=arm64 go build -o "$DIST_DIR/uptool-windows-arm64.exe" ./cmd/uptool

        echo "âœ… All binaries built successfully"
        ls -lh "$DIST_DIR"/uptool-*
        mise set CGO_ENABLED=1  # Re-enable CGO for subsequent steps

    - name: Generate checksums
      id: checksums
      shell: bash
      working-directory: ${{ steps.paths.outputs.dist }}
      run: |
        echo "ðŸ“ Generating SHA256 checksums..."
        sha256sum uptool-* > checksums.txt
        cat checksums.txt

        # Generate base64 encoded hashes for SLSA provenance
        HASHES=$(cat checksums.txt | base64 -w0)
        echo "hashes=$HASHES" >> $GITHUB_OUTPUT
        echo "âœ… Checksums generated"

    - name: Generate SBOM (SPDX)
      uses: anchore/sbom-action@fbfd9c6c189226748411491745178e0c2017392d # v0.20.10
      with:
        path: ./
        artifact-name: uptool-sbom.spdx.json
        output-file: ${{ steps.paths.outputs.dist }}/uptool-sbom.spdx.json
        format: spdx-json

    - name: Generate SBOM (CycloneDX)
      uses: CycloneDX/gh-gomod-generate-sbom@efc74245d6802c8cefd925620515442756c70d8f # v2.0.0
      with:
        version: v1
        args: mod -licenses -json -output ${{ steps.paths.outputs.dist }}/uptool-sbom.cyclonedx.json

    - name: Install Cosign
      uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0

    - name: Sign artifacts with Cosign
      shell: bash
      env:
        COSIGN_EXPERIMENTAL: 1
      working-directory: ${{ steps.paths.outputs.dist }}
      run: |
        echo "ðŸ” Signing artifacts with Cosign (keyless mode)..."

        for file in uptool-*; do
          # Skip already-signed files and non-binary files
          if [ -f "$file" ] && \
             [[ "$file" != *.sig ]] && \
             [[ "$file" != *.pem ]] && \
             [[ "$file" != *sbom* ]] && \
             [[ "$file" != checksums.txt ]]; then

            echo "  Signing $file..."
            cosign sign-blob --yes "$file" \
              --output-signature="${file}.sig" \
              --output-certificate="${file}.pem"
          fi
        done

        echo "âœ… All artifacts signed successfully"
        ls -lh *.sig *.pem

    - name: Upload artifacts
      if: inputs.upload-artifacts == 'true'
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: release-artifacts
        path: |
          ${{ steps.paths.outputs.dist }}/uptool-*
          ${{ steps.paths.outputs.dist }}/checksums.txt
        retention-days: 7

    - name: Summary
      shell: bash
      working-directory: ${{ steps.paths.outputs.dist }}
      run: |
        echo "## ðŸ“¦ Build and Sign Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Version**: ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "**Ref**: ${{ inputs.ref }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Artifacts Generated" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Binaries (7 platforms)**:" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        ls -lh uptool-* | grep -v '\.sig$' | grep -v '\.pem$' | grep -v 'sbom' | grep -v 'checksums.txt' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Security Artifacts**:" >> $GITHUB_STEP_SUMMARY
        echo "- âœ… Cosign signatures (*.sig)" >> $GITHUB_STEP_SUMMARY
        echo "- âœ… Cosign certificates (*.pem)" >> $GITHUB_STEP_SUMMARY
        echo "- âœ… SHA256 checksums (checksums.txt)" >> $GITHUB_STEP_SUMMARY
        echo "- âœ… SBOM SPDX (uptool-sbom.spdx.json)" >> $GITHUB_STEP_SUMMARY
        echo "- âœ… SBOM CycloneDX (uptool-sbom.cyclonedx.json)" >> $GITHUB_STEP_SUMMARY
