# golangci-lint configuration (v2 format)
# See https://golangci-lint.run/docs/configuration/

version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  go: "1.25"

linters:
  default: none  # Explicitly enable linters below
  enable:
    # Base linters (fast, essential)
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Official Go vet tool
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused code

    # Style & best practices
    - revive        # Fast, configurable, extensible linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - misspell      # Find misspelled English words

    # Complexity & code quality
    - gocyclo       # Cyclomatic complexity
    - gocognit      # Cognitive complexity
    - dupl          # Duplicate code detection
    - goconst       # Repeated strings that could be constants
    - gocritic      # Comprehensive Go source code linter

    # Security
    - bodyclose     # Check HTTP response bodies are closed
    - gosec         # Security-focused linter

    # Error handling
    - nilerr        # Find code returning nil when err is not nil
    - errname       # Check error type naming conventions

    # Performance
    - prealloc      # Find slice declarations that could be preallocated

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true
      settings:
        shadow:
          strict: false  # Can be noisy

    revive:
      rules:
        - name: exported
          disabled: false
        - name: unexported-return
          disabled: false
        - name: package-comments
          disabled: true  # Can be enabled later for better docs

    gosec:
      excludes:
        - G104  # Audit errors not checked (handled by errcheck)
        - G204  # Subprocess launched with variable (needed for git, pre-commit, etc)

    gocyclo:
      min-complexity: 15  # Warn on functions with complexity > 15

    gocognit:
      min-complexity: 20  # Cognitive complexity threshold

    dupl:
      threshold: 100  # Minimum token sequence for duplicate detection

    goconst:
      min-len: 3  # Minimum length of string constant
      min-occurrences: 3  # Minimum number of occurrences

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
      disabled-checks:
        - paramTypeCombine  # Can be too aggressive
        - unnamedResult     # Allow unnamed returns in some cases

    prealloc:
      simple: true  # Only check simple loops
      range-loops: true  # Check range loops
      for-loops: false  # Don't check for loops (can be noisy)

formatters:
  enable:
    - gofumpt   # Check gofmt compliance
    - gofmt     # Check goimports compliance
    - goimports # Stricter gofmt

  settings:
    gofumpt:
      extra-rules: true  # Enable extra formatting rules
      module-path: github.com/santosr2/uptool  # Module path for import grouping

issues:
  max-issues-per-linter: 0  # Unlimited
  max-same-issues: 0         # Unlimited
  uniq-by-line: true

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true

  sort-order:
    - linter
    - file

  show-stats: false
