# Hadolint configuration for uptool
# https://github.com/hadolint/hadolint

# Ignore specific rules
ignored:
  # DL3008: Pin versions in apt-get install (too strict for base images)
  - DL3008
  # DL3009: Delete apt cache after installation (handled by cleanup)
  - DL3009
  # DL3018: Pin versions in apk add (too strict for Alpine)
  - DL3018

# Trusted registries for base images
trustedRegistries:
  - docker.io
  - gcr.io
  - ghcr.io

# Failure threshold (error, warning, info, style)
failure-threshold: warning

# Inline ignore pragmas
disable-ignore-pragma: false
