# Apache SkyWalking Eyes configuration for license header checking
# See: https://github.com/apache/skywalking-eyes

header:
  license:
    spdx-id: MIT
    copyright-owner: santosr2
    copyright-year: 2024

    # MIT License header content
    content: |
      Copyright (c) 2024 santosr2

      Permission is hereby granted, free of charge, to any person obtaining a copy
      of this software and associated documentation files (the "Software"), to deal
      in the Software without restriction, including without limitation the rights
      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
      copies of the Software, and to permit persons to whom the Software is
      furnished to do so, subject to the following conditions:

      The above copyright notice and this permission notice shall be included in all
      copies or substantial portions of the Software.

      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
      SOFTWARE.

  # Scan all files by default
  paths:
    - "**"

  # Exclude these paths from license header checks
  paths-ignore:
    # Build and distribution
    - "dist/**"
    - "vendor/**"
    - "tmp/**"
    - ".mise/**"
    - "coverage/**"

    # Dependencies and lockfiles
    - "go.sum"
    - "go.mod"
    - "**/node_modules/**"

    # Documentation and metadata
    - "**/*.md"
    - "LICENSE"
    - "AUTHORS"
    - "CONTRIBUTORS.md"
    - ".github/**/*.md"
    - "docs/**/*.md"
    - "docs/**/*.txt"
    - "docs/**/*.js"
    - "docs/**/*.css"

    # Configuration files
    - "**/*.json"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.toml"
    - "**/*.ini"
    - ".gitignore"
    - ".dockerignore"
    - ".editorconfig"
    - ".gitattributes"
    - ".claudeignore"
    - ".yamllint"
    - ".env*"
    - "commitlint.config.js"
    - "crush.json*"
    - ".github/CODEOWNERS"

    # Version files
    - "internal/version/VERSION"

    # Dockerfiles (already have comments)
    - "Dockerfile*"

    # Test data and examples
    - "testdata/**"
    - "examples/**"
    - "**/testdata/**"

    # Generated files
    - "**/*.pb.go"
    - "**/*.gen.go"
    - "**/wire_gen.go"

    # Scripts
    - "**/*.sh"
    - "scripts/add-license-headers.sh"

    # IDE and editor files
    - ".vscode/**"
    - ".idea/**"
    - "**/*.swp"
    - "**/*.swo"

    # Terraform module cache
    - "**/.terraform/**"

    # OpenCode
    - ".opencode/**"

    # Claude Code
    - ".claude/**"

  # Comment on PR failures
  comment: on-failure

  # License header must be within first 80 lines
  license-location-threshold: 80

  # Language-specific comment styles
  language:
    Go:
      extensions:
        - ".go"
      comment_style_id: DoubleSlash

# Dependency license checking
dependency:
  files:
    - go.mod

# Excluded licenses (none for now, but can be configured)
# excludes:
#   - name: "some-package"
#     version: "1.0.0"
