name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving uptool! Please describe your feature request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: I'd like uptool to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      placeholder: I could also...

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      options:
        - New integration (ecosystem support)
        - Enhancement to existing integration
        - CLI improvement
        - GitHub Action improvement
        - Configuration/policy feature
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: integration
    attributes:
      label: Integration Name (if new integration)
      description: What ecosystem would this support?
      placeholder: e.g., Python pip, Go modules, Docker

  - type: textarea
    id: examples
    attributes:
      label: Example Use Case
      description: Show an example of how this would be used
      placeholder: |
        $ uptool scan
        Found: requirements.txt (python)

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: This would help because...

  - type: checkboxes
    id: willing
    attributes:
      label: Contribution
      options:
        - label: I'm willing to contribute this feature
          required: false
