apiVersion: v2
name: example-app
description: Example Helm chart showing dependency management with uptool
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - example
  - uptool
  - kubernetes

home: https://github.com/example/example-app
sources:
  - https://github.com/example/example-app

maintainers:
  - name: Example Maintainer
    email: maintainer@example.com

dependencies:
  - name: postgresql
    version: "^12.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled

  - name: redis
    version: "~18.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled

  - name: ingress-nginx
    version: ">=4.7.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled
