// Copyright (c) 2024 santosr2
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by scripts/gen_integrations.go. DO NOT EDIT.

// Package all imports all integration packages to trigger their self-registration.
// Import this package with a blank identifier to enable all integrations:
//
//	import _ "github.com/santosr2/uptool/internal/integrations/all"
package all

import (
	// Import all integration packages to trigger init() functions
	_ "github.com/santosr2/uptool/internal/integrations/actions"
	_ "github.com/santosr2/uptool/internal/integrations/asdf"
	_ "github.com/santosr2/uptool/internal/integrations/docker"
	_ "github.com/santosr2/uptool/internal/integrations/helm"
	_ "github.com/santosr2/uptool/internal/integrations/mise"
	_ "github.com/santosr2/uptool/internal/integrations/npm"
	_ "github.com/santosr2/uptool/internal/integrations/precommit"
	_ "github.com/santosr2/uptool/internal/integrations/terraform"
	_ "github.com/santosr2/uptool/internal/integrations/tflint"
)
