// Code generated by scripts/gen_integrations.go. DO NOT EDIT.

// Package all imports all integration packages to trigger their self-registration.
// Import this package with a blank identifier to enable all integrations:
//
//	import _ "github.com/santosr2/uptool/internal/integrations/all"
package all

import (
	// Import all integration packages to trigger init() functions
	_ "github.com/santosr2/uptool/internal/integrations/asdf"
	_ "github.com/santosr2/uptool/internal/integrations/helm"
	_ "github.com/santosr2/uptool/internal/integrations/mise"
	_ "github.com/santosr2/uptool/internal/integrations/npm"
	_ "github.com/santosr2/uptool/internal/integrations/precommit"
	_ "github.com/santosr2/uptool/internal/integrations/terraform"
	_ "github.com/santosr2/uptool/internal/integrations/tflint"
)
