name: 'Setup mise'
description: 'Install mise and sync tools from mise.toml'
author: 'santosr2'

inputs:
  install:
    description: 'Automatically install tools from mise.toml'
    required: false
    default: 'true'
  cache:
    description: 'Enable caching of mise tools'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Generate cache key
      id: cache-key
      shell: bash
      run: |
        # Generate cache key based on OS, architecture, and mise.toml hash
        MISE_TOML_HASH=$(sha256sum mise.toml | cut -d' ' -f1)
        CACHE_KEY="mise-${{ runner.os }}-${{ runner.arch }}-${MISE_TOML_HASH}"
        echo "key=${CACHE_KEY}" >> $GITHUB_OUTPUT
        echo "Cache key: ${CACHE_KEY}"

    - name: Cache mise tools
      uses: actions/cache@v4
      if: inputs.cache == 'true'
      with:
        path: |
          ~/.local/share/mise
          ~/.local/state/mise
          ~/.cache/mise
        key: ${{ steps.cache-key.outputs.key }}
        restore-keys: |
          mise-${{ runner.os }}-${{ runner.arch }}-

    - name: Install mise
      uses: jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3 # v2.1.4
      with:
        install: ${{ inputs.install }}
        cache: ${{ inputs.cache }}
        experimental: true

    - name: Verify mise installation
      shell: bash
      run: |
        echo "Verifying mise installation..."
        mise list
